# Default values for backendchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# image:
#   repository: 
#   pullPolicy: Always
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

global:
  ingress:
    certresolver: le

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: tfchain.dev.threefold.io
      paths:
        - /graphql
  tls:
  - hosts:
    - tfchain.dev.threefold.io
    secretName: tfchain-dev-threefold-io-tls
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# db host of the processor-db service
db_host: 10.244.1.36
# db_host:


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

threefoldVdc:
  backup: ""
