[workspace]

members = [
    "pallet-tfgrid",
    "pallet-tft-price",
    "pallet-smart-contract",
    "pallet-burning",
    "pallet-kvstore",
    "pallet-runtime-upgrade",
    "substrate-validator-set"
]
