apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: indexer-db
  name: indexer-db
spec:
  storageClassName: kadalu.replica3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
