{{- if .Values.ingress-test.enabled -}}
{{- $fullName := include "processor.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName-test }}
  labels:
    {{- include "processor.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  annotations:
    {{- with .Values.ingress-test.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
    {{- end }}
spec:
  {{- if .Values.ingress-test.tls }}
  tls:
    {{- range .Values.ingress-test.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress-test.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
