{{- if not .Values.volume.existingpersistentVolumeClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfchainindexer-volume-claim-{{ .Release.Name }}
  labels:
    {{- include "tfchainindexer.labels" . | nindent 4 }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
{{- end }}