name: Build runtime

on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.6.0
        with:
          workdir: /home/runner/work/tfchain/tfchain/substrate-node
          package: tfchain-runtime
          runtime_dir: runtime
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > tfchain-srtool-digest.json
          cat tfchain-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
      - name: Upload runtime
        uses: actions/upload-artifact@v3
        with:
          name: tfchain-runtime
          path: |
            substrate-node/${{ steps.srtool_build.outputs.wasm_compressed }}
